"""Canonical P-05 semantic catalog for types, patterns, and capability routing.

All wording and data structures in this catalog are original to this project.
The catalog contains no layout coordinates, visual tokens, specimen data, or
upstream implementation material.
"""

from __future__ import annotations

from typing import Any


def _grammar(
    capability_id: str,
    title: str,
    family: str,
    use_when: str,
    roles: tuple[str, ...],
    required_semantics: tuple[str, ...],
    edge_rules: tuple[str, ...],
    label_rules: tuple[str, ...],
    complexity_rules: tuple[str, ...],
    anti_patterns: tuple[str, ...],
    invariants: tuple[str, ...],
    negative_mutation: str,
) -> dict[str, Any]:
    return {
        "capability_id": capability_id,
        "title": title,
        "family": family,
        "use_when": use_when,
        "roles": roles,
        "required_semantics": required_semantics,
        "edge_rules": edge_rules,
        "label_rules": label_rules,
        "complexity_rules": complexity_rules,
        "anti_patterns": anti_patterns,
        "invariants": invariants,
        "negative_mutation": negative_mutation,
    }


TYPE_GRAMMARS: dict[str, dict[str, Any]] = {
    "architecture": _grammar(
        "CAP-T01", "Architecture", "topology",
        "Use for components placed inside explicit system or trust boundaries with directed dependencies.",
        ("system", "service", "actor", "data-store", "boundary"),
        ("Identify every component and boundary.", "Preserve dependency direction and boundary membership."),
        ("Use directed dependency or transfer edges.", "Keep cross-boundary edges explicit."),
        ("Use supplied component and boundary names.", "Label denied or exceptional routes explicitly."),
        ("Split by subsystem before hiding a boundary.", "Retain shared services as shared rather than duplicating them."),
        ("Do not infer deployment topology from visual proximity.", "Do not place one component in two boundaries without explicit shared scope."),
        ("minimum-two-nodes", "minimum-one-edge", "requires-boundary", "directed-edges"),
        "remove-boundaries",
    ),
    "it-current-state": _grammar(
        "CAP-T02", "IT current-state", "landscape",
        "Use for an existing technology landscape grouped by owner, business area, lifecycle, or modernization state.",
        ("system", "integration", "data-store", "owner", "boundary"),
        ("Retain owner and lifecycle state for each system.", "Preserve modernization handoffs and duplicate names as distinct IDs."),
        ("Use handoff or integration edges with direction.", "Do not turn shared ownership into containment."),
        ("Show system name plus supplied state.", "Keep owner labels separate from system labels."),
        ("Split by business area when the landscape exceeds the selected budget.", "Never collapse systems solely because labels match."),
        ("Do not present a target-state proposal as current state.", "Do not omit legacy or exception paths."),
        ("minimum-two-nodes", "requires-group", "requires-node-state", "requires-handoff"),
        "remove-node-state",
    ),
    "flowchart": _grammar(
        "CAP-T03", "Flowchart", "decision-flow",
        "Use for decisions, branches, joins, and declared outcomes in a control flow.",
        ("start", "activity", "decision", "join", "terminal"),
        ("Include at least one start and terminal.", "Make every decision outcome traceable to a declared terminal or next decision."),
        ("Direct all flow edges.", "Give every outgoing decision branch a non-empty guard label."),
        ("Use action labels for activities and outcome labels for terminals.", "Keep branch guards distinct from node labels."),
        ("Split subflows rather than shrinking branch labels.", "Retain exception outcomes even when rare."),
        ("Do not invent a missing branch.", "Do not use a decorative diamond without decision semantics."),
        ("requires-start", "requires-terminal", "requires-decision", "decision-guards", "all-nodes-reachable"),
        "remove-decision-guard",
    ),
    "sequence": _grammar(
        "CAP-T04", "Sequence", "ordered-interaction",
        "Use for time-ordered messages among actors or systems, including optional guarded fragments.",
        ("actor", "system", "participant"),
        ("Identify every participant.", "Preserve total message order and guarded fragment membership."),
        ("Use directed message edges with unique non-negative order.", "Distinguish request, response, asynchronous, and return kinds when supplied."),
        ("Use supplied participant names and message verbs.", "Keep guards on fragment or message semantics."),
        ("Split long exchanges at a stable semantic checkpoint.", "Never reorder messages to reduce crossings."),
        ("Do not infer a response that is absent.", "Do not encode time order through vertical position alone."),
        ("minimum-two-nodes", "message-edges", "unique-edge-order", "contiguous-edge-order"),
        "duplicate-message-order",
    ),
    "state-machine": _grammar(
        "CAP-T05", "State machine", "state-transition",
        "Use for finite states, guarded transitions, initial entry, terminal states, and explicit reopen paths.",
        ("initial", "state", "terminal"),
        ("Include one initial state and at least one terminal state.", "Preserve transition guards and reachability."),
        ("Use directed transition edges.", "Require a guard when multiple transitions leave the same state for different conditions."),
        ("Use state nouns or stable conditions.", "Use guard labels for transition predicates."),
        ("Split orthogonal state regions explicitly.", "Report unreachable states instead of hiding them."),
        ("Do not model activities as states without a stable condition.", "Do not create implicit transitions."),
        ("requires-initial", "requires-terminal", "transition-edges", "all-nodes-reachable"),
        "remove-terminal-state",
    ),
    "er-data-model": _grammar(
        "CAP-T06", "ER/data model", "data-model",
        "Use for entities, keys, attributes, relationships, and declared cardinalities.",
        ("entity", "associative-entity"),
        ("Retain each entity and key-bearing label.", "Preserve both ends of every supplied cardinality."),
        ("Use relationship edges whose kind states cardinality.", "Represent many-to-many ambiguity as a clarification unless junction semantics are supplied."),
        ("Use supplied entity names and key/field annotations.", "Do not rename domain terms for presentation."),
        ("Split by bounded context while retaining cross-context relationships.", "Move long field lists to annotations without dropping keys."),
        ("Do not infer foreign keys or junction entities.", "Do not use unlabeled relationship edges."),
        ("minimum-two-nodes", "entity-roles", "cardinality-edges"),
        "remove-cardinality",
    ),
    "timeline": _grammar(
        "CAP-T07", "Timeline", "temporal",
        "Use for events or milestones ordered by supplied dates or timestamps.",
        ("event", "milestone", "period"),
        ("Retain every timestamp and timezone or an explicit unknown marker.", "Preserve duplicate local times as distinct events."),
        ("Use optional chronology edges only when source order is semantic.", "Never imply causality from chronology alone."),
        ("Use supplied event labels and exact temporal values.", "Disclose timezone uncertainty."),
        ("Split by era or track without changing chronological order.", "Never drop close-together events for legibility."),
        ("Do not fabricate dates.", "Do not silently sort contradictory source order without a ledger entry."),
        ("requires-temporal-node", "chronological-node-order", "timezone-required"),
        "reverse-temporal-order",
    ),
    "swimlane": _grammar(
        "CAP-T08", "Swimlane", "owned-process",
        "Use for ordered work where actor or function ownership and cross-lane handoffs are material.",
        ("start", "activity", "decision", "artifact", "terminal"),
        ("Assign each step to exactly one lane.", "Retain lane owner, step order, and cross-lane handoffs."),
        ("Use directed handoff or flow edges.", "A cross-lane edge must connect members of different lanes."),
        ("Use action labels for steps and stable owner labels for lanes.", "Preserve Vietnamese text and numbered handoffs when supplied."),
        ("Split long processes by phase while retaining lane identity.", "Do not merge owners to reduce width."),
        ("Do not infer ownership from horizontal position.", "Do not duplicate a step into multiple lanes."),
        ("minimum-two-lanes", "lane-membership-exact", "requires-cross-lane-handoff", "unique-edge-order"),
        "remove-cross-lane-handoff",
    ),
    "quadrant": _grammar(
        "CAP-T09", "Quadrant", "quantitative-position",
        "Use for items positioned by two declared dimensions, directions, and domains.",
        ("observation", "scenario"),
        ("Declare x and y axes with domains.", "Preserve every item coordinate and out-of-domain condition."),
        ("Use no relationship edge unless source data explicitly includes one.", "Do not connect items merely because they share a quadrant."),
        ("Use supplied item labels and axis meanings.", "Name cell scenarios only when they are supplied or explicitly authorized."),
        ("Use labels or an accessible table when points overlap.", "Expand or reject out-of-domain values; never clamp silently."),
        ("Do not infer rank from area or color.", "Do not reverse an axis to improve appearance."),
        ("requires-x-y-axes", "numeric-coordinate-series", "coordinates-within-domain"),
        "move-coordinate-outside-domain",
    ),
    "radar": _grammar(
        "CAP-T10", "Radar/Spider", "multivariate-quantitative",
        "Use for multiple series measured against at least three compatible criteria on one declared scale.",
        ("series", "criterion"),
        ("Declare every criterion and a common scale.", "Preserve all series values and normalization evidence."),
        ("Use no semantic connectors between marks.", "Treat polygon closure as presentation, not an extra datum."),
        ("Use exact criterion and series labels.", "State scale and unit in accessible data."),
        ("Limit criteria or split panels before labels collide.", "Never normalize incompatible scales without approval."),
        ("Do not compare incompatible units on one radial scale.", "Do not encode magnitude through polygon area alone."),
        ("minimum-three-axes", "requires-series", "common-axis-domain", "values-within-domain"),
        "make-radar-domain-incompatible",
    ),
    "loop-flywheel": _grammar(
        "CAP-T11", "Loop/Flywheel", "cycle",
        "Use for a reinforcing or recurring cycle with ordered stations and optional shared state.",
        ("station", "shared-state"),
        ("Preserve station order and explicit cycle closure.", "Retain any shared state without making it an extra station."),
        ("Use directed cycle edges.", "Every station must participate in the same declared cycle."),
        ("Use action or state labels supplied for each station.", "Explain the reinforcing outcome separately from edge labels."),
        ("Factor repeated detail into annotations.", "Split multiple independent cycles rather than joining them decoratively."),
        ("Do not present an open chain as a flywheel.", "Do not claim causal reinforcement without source evidence."),
        ("minimum-three-nodes", "directed-edges", "requires-single-cycle"),
        "break-cycle",
    ),
    "nested": _grammar(
        "CAP-T12", "Nested", "containment",
        "Use when hierarchy is expressed primarily through explicit containment at two or more depths.",
        ("container", "item"),
        ("Retain every parent-child containment.", "Preserve depth and items outside all containers."),
        ("Use relationship edges only for non-containment relations.", "Represent containment through group membership and parent groups."),
        ("Use supplied container and item names.", "Keep depth labels optional and factual."),
        ("Split deep subtrees into linked details before flattening them.", "Retain singleton containers when semantically declared."),
        ("Do not infer containment from proximity.", "Do not accept cyclic parent groups."),
        ("requires-nested-groups", "group-membership-complete"),
        "flatten-nested-groups",
    ),
    "tree": _grammar(
        "CAP-T13", "Tree", "hierarchy",
        "Use for one-root parent-child hierarchy where every non-root item has exactly one parent.",
        ("root", "branch", "leaf"),
        ("Identify one root and preserve every parent-child relation.", "Retain leaf decisions or outcomes."),
        ("Use directed parent-to-child edges.", "Require exactly n-1 hierarchy edges for n nodes."),
        ("Use supplied item labels.", "Put branch conditions on edges when applicable."),
        ("Split at a stable subtree boundary.", "Never duplicate a multi-parent node to force tree validity."),
        ("Do not accept cycles or multiple roots.", "Do not hide a second parent."),
        ("requires-tree",),
        "add-second-parent",
    ),
    "org-chart": _grammar(
        "CAP-T14", "Org chart", "organization",
        "Use for primary reporting, ownership, routing, and separately identified escalation relationships.",
        ("person", "role", "team", "vacancy"),
        ("Preserve the primary manager relation.", "Keep escalation or dotted-line relations distinct."),
        ("Primary reporting edges form a forest or tree.", "Label non-primary relationships by kind."),
        ("Use supplied person, role, and team labels.", "Do not infer seniority from order alone."),
        ("Split by department while retaining cross-department escalation.", "Do not omit vacancies or shared roles."),
        ("Do not turn escalation into primary reporting.", "Do not assign an unprovided manager."),
        ("requires-primary-reporting", "primary-reporting-acyclic", "distinguish-nonprimary-edges"),
        "remove-primary-reporting",
    ),
    "layer-stack": _grammar(
        "CAP-T15", "Layer stack", "ordered-layers",
        "Use for ordered abstraction, enforcement, or control layers with explicit dependencies.",
        ("layer-item", "control", "cross-cutting-control"),
        ("Represent each layer as an ordered lane.", "Preserve dependencies that skip layers and cross-cutting controls."),
        ("Use directed dependency, enforcement, or compensation edges.", "Never imply adjacency is a dependency."),
        ("Use supplied layer, owner, and control names.", "Label skipped-layer dependencies explicitly."),
        ("Split control catalogs by owner while retaining layer order.", "Do not merge layers with different enforcement locations."),
        ("Do not infer a maturity ranking from vertical position.", "Do not hide cross-layer dependencies."),
        ("minimum-two-layers", "unique-layer-order", "requires-layer-members"),
        "duplicate-layer-order",
    ),
    "venn": _grammar(
        "CAP-T16", "Venn", "set-membership",
        "Use for explicit membership across two or three sets, including intersections and items outside all sets.",
        ("member", "outside-member"),
        ("Retain each set and every member's full membership vector.", "Keep outside items rather than dropping them."),
        ("Use no connector to imply membership.", "Express membership through group member IDs."),
        ("Use supplied set and member names.", "Label empty intersections when material."),
        ("Use an accessible membership table for dense sets.", "Split beyond three sets rather than drawing unreadable overlaps."),
        ("Do not infer membership from location.", "Do not duplicate one member as separate copies in intersections."),
        ("minimum-two-groups", "allows-multi-group-membership", "preserves-outside-members"),
        "remove-set-groups",
    ),
    "pyramid-funnel": _grammar(
        "CAP-T17", "Pyramid/Funnel", "ordered-quantitative",
        "Use for a ranked hierarchy or ordered conversion stages with declared values or proportions.",
        ("stage", "level"),
        ("Preserve stage order, values, missingness, and supplied ratios.", "Allow honest increases in funnel stages."),
        ("Use optional transition edges only when a process relation is supplied.", "Do not derive ratios from geometry."),
        ("Use exact stage labels, values, and units.", "Disclose whether the variant is hierarchy or conversion."),
        ("Split long stage notes into annotations.", "Never narrow a stage solely to satisfy a funnel silhouette."),
        ("Do not fabricate monotonic decrease.", "Do not imply area is proportional unless the renderer proves it."),
        ("requires-single-ordered-series", "preserves-nonmonotonic-values"),
        "remove-pyramid-series",
    ),
    "bar-chart": _grammar(
        "CAP-T18", "Bar chart", "categorical-quantitative",
        "Use for categorical value comparison with a declared unit and baseline.",
        ("category", "series"),
        ("Preserve categories, series, values, zeros, negatives, missingness, and units.", "Use a zero baseline unless an explicit approved exception is recorded."),
        ("Use no semantic connectors between bars.", "Keep grouped and stacked series identities explicit."),
        ("Use exact category, series, and unit labels.", "Provide exact accessible data values."),
        ("Split categories or use a larger size before abbreviating material labels.", "Do not aggregate without approval."),
        ("Do not truncate the baseline silently.", "Do not encode unrelated measures in one series."),
        ("requires-categorical-x-linear-y", "requires-series", "bar-zero-baseline", "series-domain-consistency"),
        "truncate-bar-baseline",
    ),
    "line-chart": _grammar(
        "CAP-T19", "Line chart", "ordered-quantitative",
        "Use for one or more quantitative series over an ordered or temporal domain.",
        ("series", "observation"),
        ("Preserve domain order, values, units, gaps, and duplicate dates.", "Keep missing values as explicit gaps."),
        ("Use no semantic connector beyond the declared series progression.", "Do not interpolate missing observations."),
        ("Use exact series, axis, unit, and date labels.", "Provide exact accessible data."),
        ("Split incompatible units into panels.", "Never sample away material points without approval."),
        ("Do not smooth or interpolate without authorization.", "Do not silently deduplicate dates."),
        ("requires-ordered-x-linear-y", "requires-series", "domain-order-valid", "missing-values-explicit"),
        "reverse-line-domain",
    ),
    "gantt": _grammar(
        "CAP-T20", "Gantt", "temporal-dependency",
        "Use for tasks or milestones with start/end times, durations, and dependencies.",
        ("task", "milestone", "phase"),
        ("Preserve start, end, timezone, order, and dependency facts.", "Reject an end before its start."),
        ("Use directed dependency edges.", "Reject dependency cycles unless the source explicitly describes an unresolved error."),
        ("Use exact task, phase, date, and timezone labels.", "Do not infer duration from visual width."),
        ("Split by phase while retaining cross-phase dependencies.", "Do not move dates to avoid overlap."),
        ("Do not fabricate missing dates.", "Do not hide a dependency cycle."),
        ("requires-task-times", "end-not-before-start", "dependency-acyclic", "timezone-required"),
        "set-end-before-start",
    ),
    "scatter-plot": _grammar(
        "CAP-T21", "Scatter plot", "paired-quantitative",
        "Use for paired observations on two declared quantitative axes.",
        ("observation", "series"),
        ("Preserve exact point count, coordinates, duplicates, and missingness.", "Declare both axis domains and units."),
        ("Use no relationship edges between observations unless source data supplies one.", "Do not connect points merely by input order."),
        ("Use exact series and axis labels.", "Provide an accessible coordinate table."),
        ("Retain up to the approved point ceiling without silent sampling.", "Use density treatment only after exact data remains accessible."),
        ("Do not replace null coordinates with zero.", "Do not claim correlation as causation."),
        ("requires-x-y-linear-axes", "numeric-coordinate-series", "scatter-missingness-valid"),
        "set-scatter-null-as-present",
    ),
    "high-level": _grammar(
        "CAP-T22", "High-Level", "platform-overview",
        "Use for an end-to-end stage or platform overview with grouped cross-cutting concerns.",
        ("stage", "capability", "cross-cutting-control", "boundary"),
        ("Retain stage order, groups, and cross-cutting control span.", "Keep overview semantics distinct from tier promotion and source-platform-consumer topology."),
        ("Use directed progression or dependency edges when supplied.", "Express cross-cutting scope through explicit membership or targets."),
        ("Use supplied stage and control labels.", "Do not add implementation details absent from the overview."),
        ("Split supporting capabilities into details while retaining the end-to-end story.", "Do not flatten cross-cutting concerns into one stage."),
        ("Do not route tier promotion here when Medallion is dominant.", "Do not invent platform components."),
        ("requires-stage-groups", "requires-progression", "requires-cross-cutting-annotation"),
        "remove-high-level-groups",
    ),
    "process": _grammar(
        "CAP-T23", "Process", "artifact-process",
        "Use for multi-actor sequential or parallel work with artifacts and handoffs.",
        ("start", "activity", "decision", "artifact", "terminal"),
        ("Retain actors, steps, artifacts, parallelism, and handoffs.", "Assign owned steps to lanes when ownership is supplied."),
        ("Use directed flow and handoff edges with stable order where sequential.", "Keep parallel branches unordered relative to each other."),
        ("Use action labels for work and noun labels for artifacts.", "Preserve supplied owner terminology."),
        ("Split by phase while retaining artifact lineage.", "Do not serialize parallel work for convenience."),
        ("Do not omit artifacts that carry state.", "Do not infer an owner from adjacency."),
        ("requires-activity", "requires-artifact", "requires-process-flow", "parallel-order-consistent"),
        "remove-process-artifact",
    ),
    "medallion": _grammar(
        "CAP-T24", "Medallion", "tier-promotion",
        "Use for records promoted through named quality or storage tiers under explicit policies.",
        ("dataset", "policy", "exception", "tier-item"),
        ("Represent tiers as ordered lanes.", "Preserve promotion, rejection, and exception paths."),
        ("Use directed promotion or rejection edges.", "Do not imply all records advance successfully."),
        ("Use supplied tier, dataset, policy, and rejection labels.", "Keep quality claims source-backed."),
        ("Split details within tiers without changing tier order.", "Retain rejected-record destinations."),
        ("Do not invent bronze/silver/gold names.", "Do not route a generic source-platform-consumer topology here."),
        ("minimum-two-tiers", "unique-layer-order", "requires-promotion-edge", "preserves-exception-path"),
        "remove-promotion-edge",
    ),
    "data-flow": _grammar(
        "CAP-T25", "Data flow", "data-movement",
        "Use for role-scoped inputs, transformations, stores, outputs, and transfers.",
        ("source", "queue", "transform", "store", "sink", "artifact"),
        ("Retain every data input, transformation, store, output, and role.", "Preserve fan-in, fan-out, capacity, and transfer direction when supplied."),
        ("Use directed transfer edges.", "Distinguish control flow from data transfer."),
        ("Use noun labels for data and verb labels for transformations.", "State queue capacity and overflow behavior when supplied."),
        ("Split by pipeline segment while preserving lineage.", "Do not aggregate records or flows without approval."),
        ("Do not show an activity-only workflow without data artifacts.", "Do not omit a bottleneck or queue capacity."),
        ("requires-source-transform-sink", "directed-edges", "data-lineage-connected"),
        "remove-data-sink",
    ),
    "dp-integration": _grammar(
        "CAP-T26", "DP integration", "integration-topology",
        "Use for source systems and partner feeds connected through a platform boundary to consumers.",
        ("source", "partner", "platform-service", "store", "consumer", "boundary"),
        ("Retain sources, platform services, consumers, boundaries, and direction.", "Preserve bidirectional integrations as two explicit directions or one declared bidirectional edge."),
        ("Use directed integration edges.", "Every source-to-consumer path must cross the declared platform boundary when that is the supplied story."),
        ("Use supplied system and interface labels.", "Keep platform boundary labels separate from component labels."),
        ("Split by source or consumer domain while retaining shared platform services.", "Do not duplicate the platform core."),
        ("Do not treat tier promotion as integration topology.", "Do not infer consumers from unused outputs."),
        ("requires-source-platform-consumer", "requires-boundary", "directed-edges"),
        "remove-platform-consumer",
    ),
    "dp-security-matrix": _grammar(
        "CAP-T27", "DP security matrix", "permission-matrix",
        "Use for complete role-by-component permission states with an explicit legend.",
        ("permission-cell", "role", "component", "legend"),
        ("Represent every declared role-component intersection exactly once.", "Preserve allow, deny, conditional, and unknown states without inference."),
        ("Use no connector to imply permission.", "Represent escalation or inheritance separately from matrix cells."),
        ("Encode each cell identity as role and component plus supplied state.", "Provide an accessible text table and legend."),
        ("Split large matrices by component domain while repeating the complete legend.", "Never omit unknown or deny cells to save space."),
        ("Do not infer missing permissions.", "Do not encode state only by color."),
        ("requires-rectangular-permission-matrix", "permission-state-enum", "requires-accessible-data"),
        "remove-permission-cell",
    ),
}


PATTERNS: dict[str, dict[str, Any]] = {
    "CAP-P01": {"name": "fan-in queue", "parent": "data-flow", "transform": "transform_fan_in_queue", "test_id": "T-PAT-CAP-P01-SEM"},
    "CAP-P02": {"name": "repeated stage slots", "parent": "process", "transform": "transform_repeated_stages", "test_id": "T-PAT-CAP-P02-SEM"},
    "CAP-P03": {"name": "unstructured to structured", "parent": "data-flow", "transform": "transform_unstructured_artifact", "test_id": "T-PAT-CAP-P03-SEM"},
    "CAP-P04": {"name": "paired policy traces", "parent": "flowchart", "transform": "transform_policy_traces", "test_id": "T-PAT-CAP-P04-SEM"},
    "CAP-P05": {"name": "secure paved road", "parent": "architecture", "transform": "transform_secure_route", "test_id": "T-PAT-CAP-P05-SEM"},
    "CAP-P06": {"name": "control catalog", "parent": "layer-stack", "transform": "transform_control_catalog", "test_id": "T-PAT-CAP-P06-SEM"},
    "CAP-P07": {"name": "compensating layers", "parent": "layer-stack", "transform": "transform_compensating_layers", "test_id": "T-PAT-CAP-P07-SEM"},
}


VARIANT_MAPPINGS: dict[str, dict[str, Any]] = {
    "CAP-V01": {"name": "neutral light", "parents": ["all"], "phase": "P-06", "implementation": "visual-mode tokens", "status": "deferred-to-authorized-phase"},
    "CAP-V02": {"name": "neutral dark", "parents": ["all"], "phase": "P-06", "implementation": "visual-mode tokens and contrast checks", "status": "deferred-to-authorized-phase"},
    "CAP-V03": {"name": "editorial", "parents": ["all"], "phase": "P-06", "implementation": "editorial composition around complete diagram", "status": "deferred-to-authorized-phase"},
    "CAP-V04": {"name": "quadrant named cells", "parents": ["quadrant"], "phase": "P-05", "implementation": "scenario-cell semantic annotations", "status": "implemented-semantic-contract"},
    "CAP-V05": {"name": "grouped bar", "parents": ["bar-chart"], "phase": "P-05", "implementation": "multiple series sharing categorical domain", "status": "implemented-semantic-contract"},
    "CAP-V06": {"name": "stacked bar", "parents": ["bar-chart"], "phase": "P-05", "implementation": "segment-to-total reconciliation", "status": "implemented-semantic-contract"},
    "CAP-V07": {"name": "pyramid hierarchy", "parents": ["pyramid-funnel"], "phase": "P-05", "implementation": "ordered level semantics", "status": "implemented-semantic-contract"},
    "CAP-V08": {"name": "conversion funnel", "parents": ["pyramid-funnel"], "phase": "P-05", "implementation": "ordered stage values and disclosed drop-off", "status": "implemented-semantic-contract"},
    "CAP-V09": {"name": "sequence fragments", "parents": ["sequence"], "phase": "P-05", "implementation": "alt/opt/loop group and guard semantics", "status": "implemented-semantic-contract"},
    "CAP-V10": {"name": "high-level alternate arrangement", "parents": ["high-level"], "phase": "P-06", "implementation": "equivalent IR with alternate layout plan", "status": "deferred-to-authorized-phase"},
    "CAP-V11": {"name": "data-lake profile", "parents": ["medallion", "dp-integration", "high-level"], "phase": "P-05", "implementation": "semantic profile selector without new type", "status": "implemented-selector"},
    "CAP-V12": {"name": "sketchy presentation", "parents": ["all"], "phase": "P-06", "implementation": "original optional presentation treatment", "status": "deferred-to-authorized-phase"},
    "CAP-V13": {"name": "terminal presentation", "parents": ["loop-flywheel"], "phase": "P-06", "implementation": "original optional terminal frame", "status": "deferred-to-authorized-phase"},
    "CAP-V14": {"name": "linked annotation", "parents": ["all"], "phase": "P-05", "implementation": "annotation target and reading-order validation", "status": "implemented-common-ir"},
    "CAP-V15": {"name": "semantic icon", "parents": ["all"], "phase": "P-09", "implementation": "approved manifest-tracked symbol with text equivalent", "status": "deferred-to-authorized-phase"},
    "CAP-V16": {"name": "sequence refresh branch", "parents": ["sequence"], "phase": "P-05", "implementation": "original combined-fragment semantic fixture", "status": "implemented-semantic-contract"},
}


DEFERRED_CLASSES: dict[str, list[tuple[str, str, str]]] = {
    "I": [
        ("draw.io XML carrier", "P-07", "bounded inert parser"),
        ("draw.io PNG embedded model", "P-07", "bounded embedded-model decoder"),
        ("draw.io SVG embedded model", "P-07", "safe XML embedded-model decoder"),
        ("draw.io page selection", "P-07", "page-preserving parser adapter"),
        ("Mermaid file carrier", "P-07", "bounded inert text parser"),
        ("Markdown Mermaid fences", "P-07", "bounded fence scanner"),
        ("Mermaid flowchart grammar", "P-07", "independent subset parser"),
        ("Mermaid sequence grammar", "P-07", "independent subset parser"),
        ("Mermaid state grammar", "P-07", "independent subset parser"),
        ("Mermaid ER grammar", "P-07", "independent subset parser"),
        ("safe redraw", "P-07", "style-discarding semantic normalization"),
        ("fidelity ledger", "P-04", "exact common-IR reconciliation"),
    ],
    "O": [
        ("format dial", "P-04/P-08", "request validation and exporter routing"),
        ("size dial", "P-04/P-06", "complexity plan then layout"),
        ("detail dial", "P-04/P-05", "fidelity-preserving semantic policy"),
        ("audience dial", "P-04/P-06", "wording depth without fact change"),
        ("diagram-only SVG", "P-08", "portable exporter"),
        ("conditional PNG", "P-08", "detected rasterizer with fallback"),
        ("accessible SVG", "P-08", "output accessibility validator"),
    ],
    "M": [
        ("none", "P-08", "complete script-free static mode"),
        ("reveal", "P-08", "deterministic one-run reveal"),
        ("step", "P-08", "controlled deterministic steps"),
        ("loop", "P-08", "decorative-only repetition"),
        ("path draw", "P-08", "bounded decorative relationship trace"),
        ("item reveal", "P-08", "ordered reveal with static fallback"),
        ("queue accumulation", "P-08", "count-preserving animation"),
        ("field population", "P-08", "static-complete text population"),
        ("policy evaluation", "P-08", "ordered policy status motion"),
        ("flow token", "P-08", "decorative hidden token"),
        ("containment reveal", "P-08", "static-complete hierarchy reveal"),
        ("audit append", "P-08", "chronological static-complete append"),
    ],
    "F": [
        ("malformed or missing input", "P-07", "named carrier failure"),
        ("unsupported Mermaid kind", "P-07", "explicit grammar boundary"),
        ("resource cap", "P-04/P-07", "bounded rejection"),
        ("ambiguous blank label", "P-07", "focused clarification"),
        ("source rot", "P-04/P-07", "explicit fidelity disposition"),
        ("executable directive", "P-07", "neutralize with zero side effect"),
        ("missing rasterizer", "P-04/P-08", "core-format fallback"),
        ("ambiguous export target", "P-08", "refuse guessed write"),
        ("editorial export boundary", "P-08", "diagram-only disclosure"),
        ("font unavailable", "P-08", "local fallback and warning"),
        ("motion failure", "P-08", "complete static fallback"),
        ("reduced motion or print", "P-08", "complete static state"),
        ("complexity budget", "P-04", "larger/split/narrow clarification"),
        ("material ambiguity", "P-04/P-05", "ask or bounded assumption"),
    ],
}


SPECIMEN_GROUPS = (
    {"id": "SPEC-BASE", "count": 81, "capabilities": ["CAP-V01", "CAP-V02", "CAP-V03"] + [f"CAP-T{i:02d}" for i in range(1, 28)], "mapping": "27 type grammars plus three later visual modes"},
    {"id": "SPEC-HIGH-VERTICAL", "count": 3, "capabilities": ["CAP-T22", "CAP-V10"], "mapping": "High-Level equivalent IR; layout deferred to P-06"},
    {"id": "SPEC-DATA-LAKE", "count": 3, "capabilities": ["CAP-V11", "CAP-T22", "CAP-T24", "CAP-T26"], "mapping": "profile selector chooses existing parent by dominant semantics"},
    {"id": "SPEC-SEQUENCE-BRANCH", "count": 3, "capabilities": ["CAP-T04", "CAP-V09", "CAP-V16"], "mapping": "original combined-fragment semantic fixture"},
    {"id": "SPEC-IMPORT", "count": 2, "capabilities": ["CAP-I01", "CAP-I05", "CAP-I11", "CAP-I12"], "mapping": "carrier behavior deferred to P-07; fidelity core exists"},
    {"id": "SPEC-QUADRANT", "count": 1, "capabilities": ["CAP-T09", "CAP-V04"], "mapping": "named-cell scenario annotations"},
    {"id": "SPEC-LOOP-TERMINAL", "count": 1, "capabilities": ["CAP-T11", "CAP-V13"], "mapping": "loop semantics now; terminal presentation deferred"},
    {"id": "SPEC-ANIMATED-PATTERNS", "count": 3, "capabilities": ["CAP-P01", "CAP-P04", "CAP-P05", "CAP-M02", "CAP-M03", "CAP-M04"], "mapping": "semantic transformations now; motion deferred to P-08"},
)


def build_capability_map() -> dict[str, dict[str, Any]]:
    mapping: dict[str, dict[str, Any]] = {}
    for diagram_type, grammar in TYPE_GRAMMARS.items():
        capability_id = grammar["capability_id"]
        mapping[capability_id] = {
            "class": "canonical-type",
            "parents": [diagram_type],
            "phase_owner": "P-05",
            "implementation": f"TYPE_GRAMMARS[{diagram_type}] plus validate_typed_ir",
            "selector": "semantic route candidate",
            "fallback": "needs-clarification or invalid; never substitute another type",
            "test_id": f"T-TYPE-{int(capability_id[-2:]):02d}-SEM",
            "status": "implemented-semantic-grammar",
        }
    for capability_id, variant in VARIANT_MAPPINGS.items():
        mapping[capability_id] = {
            "class": "variant",
            "parents": variant["parents"],
            "phase_owner": variant["phase"],
            "implementation": variant["implementation"],
            "selector": f"explicit capability {capability_id} or matching semantic profile",
            "fallback": "preserve parent semantics and disclose unavailable presentation behavior",
            "test_id": f"T-VAR-{capability_id}-MAP",
            "status": variant["status"],
        }
    for capability_id, pattern in PATTERNS.items():
        mapping[capability_id] = {
            "class": "semantic-pattern",
            "parents": [pattern["parent"]],
            "phase_owner": "P-05",
            "implementation": pattern["transform"],
            "selector": f"explicit pattern {capability_id} with complete required fields",
            "fallback": "invalid or needs-clarification; never create a new type",
            "test_id": pattern["test_id"],
            "status": "implemented-transformation",
        }
    for prefix, entries in DEFERRED_CLASSES.items():
        class_name = {"I": "import-fidelity", "O": "output", "M": "motion", "F": "failure"}[prefix]
        for index, (name, phase, implementation) in enumerate(entries, 1):
            capability_id = f"CAP-{prefix}{index:02d}"
            implemented = phase in {"P-04", "P-04/P-05"} or (prefix == "O" and index in {3})
            mapping[capability_id] = {
                "class": class_name,
                "parents": ["cross-type"],
                "phase_owner": phase,
                "implementation": implementation,
                "selector": f"request or environment condition for {name}",
                "fallback": "named non-destructive outcome with no guessed artifact",
                "test_id": f"T-{prefix}-{capability_id}-MAP",
                "status": "implemented-contract" if implemented else "deferred-to-authorized-phase",
            }
    return dict(sorted(mapping.items()))


CAPABILITY_MAP = build_capability_map()


def expected_capability_ids() -> set[str]:
    result = {f"CAP-T{i:02d}" for i in range(1, 28)}
    result.update(f"CAP-V{i:02d}" for i in range(1, 17))
    result.update(f"CAP-P{i:02d}" for i in range(1, 8))
    result.update(f"CAP-I{i:02d}" for i in range(1, 13))
    result.update(f"CAP-O{i:02d}" for i in range(1, 8))
    result.update(f"CAP-M{i:02d}" for i in range(1, 13))
    result.update(f"CAP-F{i:02d}" for i in range(1, 15))
    return result


__all__ = [
    "CAPABILITY_MAP",
    "PATTERNS",
    "SPECIMEN_GROUPS",
    "TYPE_GRAMMARS",
    "VARIANT_MAPPINGS",
    "expected_capability_ids",
]
